### PR TITLE
fixing audit issues with async

### PR DESCRIPTION
**Pull request by Tobias4872**
upgrade async library to a version without audit issues; tests are running fine.

### CODE REVIEW

**Review by kibertoad — APPROVED** [review]

**Comment by GoetzGoerisch** [comment]
@kibertoad just out of curiosity. Why you didn't merge the PR #406 prepared by  @mceachen?

**Comment by WilliamRADFunk** [comment]
Yes, a new release please. We have many Component Governance alerts hinging on this being available.

**Comment by jaishirole** [comment]
Hello @kibertoad Our pipelines currently stand broken due to unavailability of a fixed release of `async`. Is there any ETA that we  can hope to see the release cut?

**Comment by VamseeInala** [comment]
+1 Please let us know when this fix will be available

**Comment by mde** [comment]
I'll get this done today. Apologies for the delay.

**Comment by shreya410** [comment]
Thank you so much. :)

**Comment by mde** [comment]
Pushed to NPM, v10.8.5. Again, apologies for the delay y'all.

**Pull request merged**
