### PR TITLE
Fix file task prereq handling (redo of #387)

### LINKED ISSUE #423: File task dependency handling buggy
MWE:
```js
const fs = require('fs');
const { directory, file } = require('jake');

directory('build');

file('build/output1.txt', ['build'], () => {
  console.log('writing build/output1.txt');
  fs.writeFileSync('build/output1.txt', 'Contents of build/output1.txt');
});

file('build/output2a.txt', ['build/output1.txt'], () => {
  console.log('writing build/output2a.txt');
  fs.writeFileSync('build/output2a.txt', 'Contents of build/output2a.txt');
});

file('build/output2b.txt', ['build/output1.txt'], () => {
  console.log('writing build/output2b.txt');
  fs.writeFileSync('build/output2b.txt', 'Contents of build/output2b.txt');
});

file('build/output3.txt', [ 'build/output2a.txt', 'build/output2b.txt'], () => {
  console.log('writing build/output3.txt');
  fs.writeFileSync('build/output3.txt', 'Contents of build/output3.txt');
});
```
Starting from a state where `build/output1.txt` (or `build` entirely)  is missing, everything is built with `jake build/output3.txt` as desired. But if only `build/output2b.txt` or `build/output3.txt` are missing, nothing gets rebuild. Yes, `jake build/output3.txt` does not even build `build/output3.txt`. If `build/output1.txt` is `touch`ed, only `build/output2a.txt` is rebuilt by `jake build/output3.txt`. No errors are shown for any of these cases.

This might be a duplicate of #388, but that has a rather vague description, so I'm not sure. If it is, this MWE might be a starting point for a test case for #387.

### PR DESCRIPTION
**Pull request by martinholters**
This is a redo of #387 by (which seems to have stalled) with a test added. Thanks to @colinshr for the fix!

Fixes #423.

### CODE REVIEW

**Comment by martinholters** [comment]
Gentle bump. I'd really like to see #423 fixed.

**Comment by colinshr** [comment]
You can use my fork if this doesn't get resolved.
https://github.com/colinshr/jake

**Comment by martinholters** [comment]
Gentle bump again.

**Comment by mde** [comment]
Thanks for your patience!

**Comment by mde** [comment]
Published to NPM in `jake@10.8.6`.

**Pull request merged**
