### PR TITLE
bash auto completion

### PR DESCRIPTION
**Pull request by kedashoe**
An attempt at bash auto completion. Some notes:
- The basic idea is to run the actual Jakefile with some new flags to generate completions (ie, no new parsing code)
- I added an `internalOpts` function to `program.js` so we can tell jake in the `auto_complete.js` wrapper what we are doing
- I don't know anything about auto completion in other shells/OSes (I'm on a debian based system), but I tried to do as much in javascript as possible with the idea that the code could be re-used in other environments. I actually think I may have gone too far here, as some quirks of bash are handled that I doubt would be applicable elsewhere
- Things were complicated quite a bit by needing to support ':' in bash completion. There are some links to stackoverflow answers that helped in `bash_completion.sh`
- Things also seem to be working if a project does not use a default Jakefile. At first, completions will be default bash completions, but as soon as we've got `-f path/to/custom-jakefile`, it will start using targets from the custom jakefile for completions
- ~~I did not add any tests, however I ran the current test suite and it appears nothing is broken. To test for now, just source `bin/bash_completion.js` and test with an executable `jake` (ie if you have it globally installed, or you have another project that uses jake)~~ EDIT: test included in task_base.js
- not using COMP_CWORD or COMP_POINT
- Looks like the README is mostly just a link to the docs. I have not looked into updating those. Basically can say something like https://github.com/creationix/nvm/blob/master/README.markdown#bash-completion

Let me know what you guys think!

### CODE REVIEW

**Comment by mde** [comment]
This looks great. A couple of things:

- It would be really nice to have at least one smoke test of this, so we make sure we don't regress on it. 

- Also (and this is very nit-picky), I notice there are some snake_case variables in this PR. All the Jake code style is pretty coherent. We stick closely to something like this: https://github.com/geddy/js-styleguide

This is pretty fantastic. If you could tweak the code style, and add a basic smoke test, I'd be very excited to merge this PR!

**Comment by kedashoe** [comment]
Alright PR updated. JS variable style fixed. I added some tests to `task_base.js` which seemed the best place for them without creating a new test file. Not *perfect*, better would be to create a shell script that sources `bash_complete.sh`.. and calls `_auto_jake` and outputs those results.. which are then checked by the test runner.. or something like that? Maybe could submit a separate PR for that later if I find some more time. Let me know if anything else for now.

**Comment by busticated** [comment]
hey there @kedashoe - this looks _awesome_ and is something i've really been wanting myself. anything i can do to help land this? could you possibly rebase it / bring it up to date with current jake master? cc @mde

**Comment by kedashoe** [comment]
@busticated rebased, ran test suite, looks like everything still passing :fireworks:

**Comment by busticated** [comment]
@kedashoe nice, thanks! i'll pull it down and try it out :)

**Comment by boblauer** [comment]
Is there still a possibility of this getting merged?

**Comment by mde** [comment]
Sorry to take a while to get this merged. Thanks!

**Pull request merged**
