### PR TITLE
Ignore properties defined on EventEmitter

### PR DESCRIPTION
**Pull request by bradford-fisher**
Fixes [#374](https://github.com/jakejs/jake/issues/374)

### CODE REVIEW

**Comment by kibertoad** [comment]
Thanks!

**Comment by bradford-fisher** [comment]
Happy to help!

**Comment by kibertoad** [comment]
@bradford-fisher 
Gah, linting is now broken, see https://travis-ci.org/github/jakejs/jake/builds/677443816

Could you fix it?

**Comment by bradford-fisher** [comment]
@kibertoad Sure can. Sorry. Forgot to run the linter.

**Pull request merged**
