### PR TITLE
Update file_task.js

### PR DESCRIPTION
**Pull request by colinshr**
fix file task not detecting and finishing parent of dep

### CODE REVIEW

**Comment by colinshr** [comment]
fixed when using on file task dep and it not calling parent when done

**Comment by colinshr** [comment]
adding support to overwrite externally

**Comment by mde** [comment]
This looks great. Any way you could include a test for the FileTask problem?

**Comment by colinarktrade** [comment]
I don't have a test, I'm using it in a very different way by adding all tasks in my own object, and calling jake.run directly at the end.
I've also added subdir support and aws/heroku/deploy.
If you are interested we can have a call to show you all the code and maybe you will want to use it.

**Pull request closed without merging**
